banner:
  charset: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8010

spring:
  application:
    name: netty-service
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

netty:
  server:
    port: 9876
    uploadPath: /root/log-file/