// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netty/Request.proto

package com.lenovo.cloud.netty.protobuf;

public final class RequestFile {
  private RequestFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fileName = 1;</code>
     */
    String getFileName();
    /**
     * <code>string fileName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int64 starPos = 2;</code>
     */
    long getStarPos();

    /**
     * <code>bytes bytes = 3;</code>
     */
    com.google.protobuf.ByteString getBytes();

    /**
     * <code>int32 endPos = 4;</code>
     */
    int getEndPos();

    /**
     * <code>string fileType = 5;</code>
     */
    String getFileType();
    /**
     * <code>string fileType = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();

    /**
     * <code>int64 fileSize = 6;</code>
     */
    long getFileSize();

    /**
     * <code>string filePath = 7;</code>
     */
    String getFilePath();
    /**
     * <code>string filePath = 7;</code>
     */
    com.google.protobuf.ByteString
        getFilePathBytes();
  }
  /**
   * Protobuf type {@code RequestMsg}
   */
  public  static final class RequestMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMsg)
      RequestMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMsg.newBuilder() to construct.
    private RequestMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMsg() {
      fileName_ = "";
      bytes_ = com.google.protobuf.ByteString.EMPTY;
      fileType_ = "";
      filePath_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 16: {

              starPos_ = input.readInt64();
              break;
            }
            case 26: {

              bytes_ = input.readBytes();
              break;
            }
            case 32: {

              endPos_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              fileType_ = s;
              break;
            }
            case 48: {

              fileSize_ = input.readInt64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestFile.internal_static_RequestMsg_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestFile.internal_static_RequestMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMsg.class, Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile Object fileName_;
    /**
     * <code>string fileName = 1;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARPOS_FIELD_NUMBER = 2;
    private long starPos_;
    /**
     * <code>int64 starPos = 2;</code>
     */
    public long getStarPos() {
      return starPos_;
    }

    public static final int BYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>bytes bytes = 3;</code>
     */
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    public static final int ENDPOS_FIELD_NUMBER = 4;
    private int endPos_;
    /**
     * <code>int32 endPos = 4;</code>
     */
    public int getEndPos() {
      return endPos_;
    }

    public static final int FILETYPE_FIELD_NUMBER = 5;
    private volatile Object fileType_;
    /**
     * <code>string fileType = 5;</code>
     */
    public String getFileType() {
      Object ref = fileType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      }
    }
    /**
     * <code>string fileType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESIZE_FIELD_NUMBER = 6;
    private long fileSize_;
    /**
     * <code>int64 fileSize = 6;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    public static final int FILEPATH_FIELD_NUMBER = 7;
    private volatile Object filePath_;
    /**
     * <code>string filePath = 7;</code>
     */
    public String getFilePath() {
      Object ref = filePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <code>string filePath = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (starPos_ != 0L) {
        output.writeInt64(2, starPos_);
      }
      if (!bytes_.isEmpty()) {
        output.writeBytes(3, bytes_);
      }
      if (endPos_ != 0) {
        output.writeInt32(4, endPos_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileType_);
      }
      if (fileSize_ != 0L) {
        output.writeInt64(6, fileSize_);
      }
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, filePath_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (starPos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, starPos_);
      }
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bytes_);
      }
      if (endPos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, endPos_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileType_);
      }
      if (fileSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, fileSize_);
      }
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, filePath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestMsg)) {
        return super.equals(obj);
      }
      RequestMsg other = (RequestMsg) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (getStarPos()
          != other.getStarPos()) return false;
      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (getEndPos()
          != other.getEndPos()) return false;
      if (!getFileType()
          .equals(other.getFileType())) return false;
      if (getFileSize()
          != other.getFileSize()) return false;
      if (!getFilePath()
          .equals(other.getFilePath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + STARPOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStarPos());
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (37 * hash) + ENDPOS_FIELD_NUMBER;
      hash = (53 * hash) + getEndPos();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType().hashCode();
      hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSize());
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMsg)
        RequestMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestFile.internal_static_RequestMsg_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestFile.internal_static_RequestMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMsg.class, Builder.class);
      }

      // Construct using com.lenovo.cloud.netty.protobuf.RequestFile.RequestMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        fileName_ = "";

        starPos_ = 0L;

        bytes_ = com.google.protobuf.ByteString.EMPTY;

        endPos_ = 0;

        fileType_ = "";

        fileSize_ = 0L;

        filePath_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestFile.internal_static_RequestMsg_descriptor;
      }

      @Override
      public RequestMsg getDefaultInstanceForType() {
        return RequestMsg.getDefaultInstance();
      }

      @Override
      public RequestMsg build() {
        RequestMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RequestMsg buildPartial() {
        RequestMsg result = new RequestMsg(this);
        result.fileName_ = fileName_;
        result.starPos_ = starPos_;
        result.bytes_ = bytes_;
        result.endPos_ = endPos_;
        result.fileType_ = fileType_;
        result.fileSize_ = fileSize_;
        result.filePath_ = filePath_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMsg) {
          return mergeFrom((RequestMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMsg other) {
        if (other == RequestMsg.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getStarPos() != 0L) {
          setStarPos(other.getStarPos());
        }
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        if (other.getEndPos() != 0) {
          setEndPos(other.getEndPos());
        }
        if (!other.getFileType().isEmpty()) {
          fileType_ = other.fileType_;
          onChanged();
        }
        if (other.getFileSize() != 0L) {
          setFileSize(other.getFileSize());
        }
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object fileName_ = "";
      /**
       * <code>string fileName = 1;</code>
       */
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private long starPos_ ;
      /**
       * <code>int64 starPos = 2;</code>
       */
      public long getStarPos() {
        return starPos_;
      }
      /**
       * <code>int64 starPos = 2;</code>
       */
      public Builder setStarPos(long value) {
        
        starPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 starPos = 2;</code>
       */
      public Builder clearStarPos() {
        
        starPos_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 3;</code>
       */
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 3;</code>
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 3;</code>
       */
      public Builder clearBytes() {
        
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }

      private int endPos_ ;
      /**
       * <code>int32 endPos = 4;</code>
       */
      public int getEndPos() {
        return endPos_;
      }
      /**
       * <code>int32 endPos = 4;</code>
       */
      public Builder setEndPos(int value) {
        
        endPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 endPos = 4;</code>
       */
      public Builder clearEndPos() {
        
        endPos_ = 0;
        onChanged();
        return this;
      }

      private Object fileType_ = "";
      /**
       * <code>string fileType = 5;</code>
       */
      public String getFileType() {
        Object ref = fileType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fileType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileType = 5;</code>
       */
      public Builder setFileType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 5;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 5;</code>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileType_ = value;
        onChanged();
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>int64 fileSize = 6;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>int64 fileSize = 6;</code>
       */
      public Builder setFileSize(long value) {
        
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fileSize = 6;</code>
       */
      public Builder clearFileSize() {
        
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      private Object filePath_ = "";
      /**
       * <code>string filePath = 7;</code>
       */
      public String getFilePath() {
        Object ref = filePath_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string filePath = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filePath = 7;</code>
       */
      public Builder setFilePath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 7;</code>
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 7;</code>
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMsg)
    }

    // @@protoc_insertion_point(class_scope:RequestMsg)
    private static final RequestMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestMsg();
    }

    public static RequestMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMsg>
        PARSER = new com.google.protobuf.AbstractParser<RequestMsg>() {
      @Override
      public RequestMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public RequestMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023netty/Request.proto\"\204\001\n\nRequestMsg\022\020\n\010" +
      "fileName\030\001 \001(\t\022\017\n\007starPos\030\002 \001(\003\022\r\n\005bytes" +
      "\030\003 \001(\014\022\016\n\006endPos\030\004 \001(\005\022\020\n\010fileType\030\005 \001(\t" +
      "\022\020\n\010fileSize\030\006 \001(\003\022\020\n\010filePath\030\007 \001(\tB.\n\037" +
      "com.lenovo.cloud.netty.protobufB\013Request" +
      "Fileb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMsg_descriptor,
        new String[] { "FileName", "StarPos", "Bytes", "EndPos", "FileType", "FileSize", "FilePath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
